### ISSUE TITLE
Wrong path specified during frames extraction

### ISSUE THREAD

**Issue by danchern97** [facebookresearch/open-eqa#13]
Hey, I noticed the following issue when I tried to run `python data/hm3d/extract-frames.py`:
<img width="1194" alt="Снимок экрана 2024-06-06 в 14 29 57" src="https://github.com/facebookresearch/open-eqa/assets/14604017/58a7180f-ed80-4a90-b3a7-b4a3fd7bd2ba">

In the folder data/frames/hm3d-v0/021-hm3d-LT9Jq6dN3Ea, a file which should specify the scene file (`00000.pkl`) has attribute `scene_id: datasets01/hm3d/090121/val/00862-LT93q63E/LT9Jq60N3Ea.basis.glb` instead of correct one `data/scene_datasets/hm3d/val/00862-LT93q63E/LT9Jq60N3Ea.basis.glb`. This may be in other files too, I haven't checked that.

**Comment by arjunmajum** [comment]
This issue should be fixed.

Start with step 3 in option 2 [here](https://github.com/facebookresearch/open-eqa/blob/main/data/README.md#hm3d) and try again. Specifically, re-download the agent state information and confirm that you have the correct checksum:

```bash
md5sum open-eqa-hm3d-frames-v0.tgz  # 286aa5d2fda99f4ed1567ae212998370
```
