### ISSUE TITLE
Code of the Scene-graph based method

### ISSUE THREAD

**Issue by ZCMax** [facebookresearch/open-eqa#3]
Thanks for your great work! I wonder whether the code about scene-graph based method will  be release?

**Comment by keke-220** [comment]
> Thanks for your great work! I wonder whether the code about scene-graph based method will be release?

Hey, thanks for your interest! There are two SG-based methods in our paper: one is ConceptGraph (please find their code [here](https://github.com/concept-graphs/concept-graphs)), the other one is SVM (see [this PR](https://github.com/facebookresearch/home-robot/commit/f724f3bd17f4783d4de2a7e04816cf4fb0e285a2) in the [HomeRobot](https://github.com/facebookresearch/home-robot) repo). We use the original implementation of both.
